version: '3'

services:
  node-hello:
    image: jaaacki/node-hello
    container_name: node-hello
    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=node-hello"
      - "traefik.frontend.rule=Host:hello.us.sg"
      - "traefik.port=8080"
      - "traefik.docker.network=reverse-proxy"
    networks:
      reverse-proxy:
        external:
          name: reverse-proxy